apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: loadvnif6018-tenant-app
    appstudio.openshift.io/component: loadvnif6018-tenant-component
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: loadvnif6018-tenant-component
  namespace: loadvnif6018-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_devfile-samples_devfile-sample-python-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/devfile-samples/devfile-sample-python-basic
